services:
  core-service:
    command: npm run dev
    volumes:
      - ./apps/core-service:/app
      - /app/node_modules # Anonymous volume to prevent local node_modules from overwriting the container's

  frontend:
    command: npm run dev
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next

  # NEW: Added development settings for the prediction-service
  prediction-service:
    # The command uses --reload to automatically restart the server when code changes
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mount the local directory into the container for live code changes
      - ./apps/prediction-service:/app
