services:
  postgres:
    ports:
      - "5432:5432"

  core-service:
    command: npm run dev
    volumes:
      - ./apps/core-service:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rentverse_core.rule=Host(`core_rv.ilhamdean.cloud`)"
      - "traefik.http.routers.rentverse_core.entrypoints=websecure"
      - "traefik.http.routers.rentverse_core.tls.certresolver=le"
      - "traefik.http.services.myapp.loadbalancer.server.port=8080"

  frontend:
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    env_file: ./apps/frontend/.env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rentverse_frontend.rule=Host(`front_rv.ilhamdean.cloud`)"
      - "traefik.http.routers.rentverse_frontend.entrypoints=websecure"
      - "traefik.http.routers.rentverse_frontend.tls.certresolver=le"
      - "traefik.http.services.myapp.loadbalancer.server.port=3000"

  prediction-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/prediction-service:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rentverse_prediction.rule=Host(`pred_rv.ilhamdean.cloud`)"
      - "traefik.http.routers.rentverse_prediction.entrypoints=websecure"
      - "traefik.http.routers.rentverse_prediction.tls.certresolver=le"
      - "traefik.http.services.myapp.loadbalancer.server.port=8000"

  minio:
    labels:
      - "traefik.enable=true"

      # --- Router untuk API (port 9000) ---
      - "traefik.http.routers.rentverse_minio_api.rule=Host(`minio_rv.ilhamdean.cloud`)"
      - "traefik.http.routers.rentverse_minio_api.entrypoints=websecure"
      - "traefik.http.routers.rentverse_minio_api.tls.certresolver=le"
      - "traefik.http.services.rentverse_minio_api.loadbalancer.server.port=9000"

      # --- Router untuk Console (port 9090) ---
      - "traefik.http.routers.rentverse_minio_console.rule=Host(`minio_console_rv.ilhamdean.cloud`)"
      - "traefik.http.routers.rentverse_minio_console.entrypoints=websecure"
      - "traefik.http.routers.rentverse_minio_console.tls.certresolver=le"
      - "traefik.http.services.rentverse_minio_console.loadbalancer.server.port=9001"
