services:
  postgres:
    ports:
      - "5432:5432"
    networks:
      - rentverse_network
      - tunnel

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - rentverse_network
      - tunnel

  core-service:
    command: npm run dev
    volumes:
      - ./apps/core-service:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    env_file: ./apps/core-service/.env
    networks:
      - rentverse_network
      - tunnel

  frontend:
    command: npm run dev
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file: ./apps/frontend/.env.local
    networks:
      - rentverse_network
      - tunnel

  prediction-service:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/prediction-service:/app
    ports:
      - "8000:8000"
    env_file: ./apps/prediction-service/.env
    networks:
      - rentverse_network
      - tunnel

networks:
  tunnel:
    external: true
